name: caching dependencies

on:
  push:
    branches:
        - main

jobs:
  build: 
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.17'
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: | 
            C:\Users\runneradmin\go\pkg\mod
            C:\Users\runneradmin\go\bin
          key: ${{ runner.os }}-go-${{ hashFiles('subdir/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download
        working-directory: ./subdir
          

    
    
