name: specifying version and architecture

on:
  push:
    branches:
        -  main
jobs:
  build:
    runs-on: windows-latest

steps:
  - uses: actions/checkout@v4
  - name: Set up JDK 11 for x64
    uses: actions/setup-java@v4
    with:
      java-version: '11'
      distribution: 'temurin'
      architecture: x64
