name: single version of node.js

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install dependencies
        run: npm install
        working-directory: ./js-2
        
      - name: Build Project
        run: npm run build --if-present
        working-directory: ./js-2

      - name: Run tests
        run: npm test
        working-directory: ./js-2
       
