name: Upload artifact from Ubuntu

on: [push]

jobs:
  upload-pester-results:
    name: Run Pester and upload results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pester
        shell: pwsh
        run: Install-Module -Name Pester -Force -SkipPublisherCheck
      - name: List files in the current directory
        shell: pwsh
        run: Get-ChildItem -Recurse
      - name: Check if Unit.Tests.ps1 exists
        shell: pwsh
        run: |
          if (!(Test-Path -Path "Unit.Tests.ps1")) {
            throw "Unit.Tests.ps1 not found."
          }
      - name: Test with Pester
        shell: pwsh
        run: Invoke-Pester Unit.Tests.ps1 -Passthru | Export-CliXml -Path Unit.Tests.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-Unit-Tests
          path: Unit.Tests.xml
        if: ${{ always() }}
