name: S3 deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify current directory
        run: |
          pwd
          ls -l

     - name: Set up AWS CLI
       uses: aws-actions/configure-aws-credentials@v2
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

      - name: Check AWS CLI version
        run: aws --version
        
      - name: Check AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID set? ${{ secrets.AWS_ACCESS_KEY_ID != '' }}"
          echo "AWS_SECRET_ACCESS_KEY set? ${{ secrets.AWS_SECRET_ACCESS_KEY != '' }}"

      - name: Sync files to S3
        run: |
          aws s3 sync ./Files s3://chaitu-401 --delete
