name: S3 deployment

on:
  push:
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAS66UC3NRYRQXXAW3
          aws-secret-access-key: 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
          aws-region: ap-south-1

      - name: Sync files to S3
        run: |
          aws s3 sync ./Files s3://chaitu-401 --delete
